Fix bitwise/boolean error
I have separated out this one change from the others I proposed.

I was getting the following error:
error: use of bitwise '|' with boolean operands

Adding one more '|' fixed the problem.  

I don't know CPP, so please make sure this makes sense.